#!/usr/bin/env python3
"""Generate and run a broad, reproducible ASTRO optimizer ablation campaign.

This script deliberately does not implement another optimizer.  It orchestrates
``scripts/astro_lab.py`` using its tested optimizer registry and resumable state,
so the same experimental engine is used for Muon, NorMuon, AdaMuon, SOAP and
ASTRO variants.

Design goals
------------
1. Search the legitimate hyperparameter space of each optimizer rather than
   comparing one hand-picked setting.
2. Separate *configuration discovery* from *held-out evaluation*.
3. Cover ASTRO's proposed components individually and in selected combinations.
4. Keep every job independently resumable and write an auditable manifest.
5. Support sharding so several Colab T4 sessions can run disjoint work.

The runner writes a JSONL audit log.  Each job also gets its own work directory,
which prevents configuration collisions and makes it safe to rerun one shard.

Typical Colab usage
-------------------

    python scripts/ablation_suite.py --suite primary --shard 0/3 \
        --work-root /content/drive/MyDrive/astro/ablation

    python scripts/ablation_suite.py --suite mechanisms --shard 1/3 \
        --work-root /content/drive/MyDrive/astro/ablation

    python scripts/ablation_suite.py --suite robustness --shard 2/3 \
        --work-root /content/drive/MyDrive/astro/ablation

Use ``--dry-run`` first.  The default timeout is deliberately conservative;
the inner ``astro_lab.py`` process checkpoints after every completed run.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import shlex
import subprocess
import sys
import time
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Iterable


# ---------------------------------------------------------------------------
# Search spaces. Values are intentionally explicit and reviewable rather than
# being generated by an opaque random search.
# ---------------------------------------------------------------------------

MUON_FAMILY_LR = (0.003, 0.006, 0.012, 0.024, 0.048, 0.096)
MUON_FAMILY_WD = (0.0, 0.003, 0.01, 0.03, 0.1)
SCALAR_MULTS = (0.25, 0.35, 0.4369, 0.55, 0.75)

# ASTRO's matrix path variants currently exposed by astro_lab.py.  These names
# are intentionally kept in one place so a removed/renamed variant becomes an
# obvious manifest diff rather than a silent change in the campaign.
ASTRO_VARIANTS = (
    "astro",
    "astro_pinned",
    "astro_trust",
    "astro_cautious",
    "astro_converging",
    "astro_gamma25",
    "astro_gamma50",
    "astro_gamma0",
    "astro_equil",
    "astro_plain_wd",
    "astro_wd_rescaled",
    "astro_muon_betas",
    "astro_v2",
    "astro_v2_gamma0",
    "astro_nosplit",
    "astro_split100",
    "astro_split300",
)
BASELINES = ("muon", "normuon", "adamuon", "soap")


@dataclass(frozen=True)
class Job:
    job_id: str
    suite: str
    optimizer: str
    size: str
    steps: int
    seed: int
    trials: int
    pins: tuple[str, ...]
    purpose: str
    shard_key: str

    def command(self, script: Path, work_dir: Path) -> list[str]:
        cmd = [
            sys.executable,
            str(script),
            "--mode",
            "scaling",
            "--sizes",
            self.size,
            "--steps",
            str(self.steps),
            "--optimizers",
            self.optimizer,
            "--trials",
            str(self.trials),
            "--seeds",
            str(self.seed),
            "--work-dir",
            str(work_dir),
        ]
        for pin in self.pins:
            cmd.extend(["--pin", pin])
        return cmd


def _job_id(*parts: object) -> str:
    raw = "|".join(map(str, parts))
    return hashlib.sha1(raw.encode("utf-8")).hexdigest()[:12]


def _jobs_primary() -> list[Job]:
    """Deep 124M comparison: broad tuning plus all major ASTRO variants."""
    jobs: list[Job] = []

    # Baselines get a broad explicit LR/WD matrix. This is a sensitivity study,
    # not the final held-out result; later scripts freeze the winning region.
    for opt in BASELINES:
        for lr in MUON_FAMILY_LR:
            for wd in MUON_FAMILY_WD:
                for scalar in (0.35, 0.4369, 0.55):
                    jobs.append(_make(
                        "primary", opt, "124M", 900, 0, 1,
                        (f"lr={lr}", f"weight_decay={wd}", f"scalar_lr_mult={scalar}"),
                        "baseline lr/weight-decay/scalar sensitivity",
                    ))

    # Every ASTRO variant receives its own LR/WD/scalar sweep.  The variant
    # itself defines which structural changes are enabled; the search does not
    # get a special optimizer-only tuning budget.
    for variant in ASTRO_VARIANTS:
        for lr in MUON_FAMILY_LR:
            for wd in (0.0, 0.003, 0.01, 0.03):
                for scalar in SCALAR_MULTS:
                    jobs.append(_make(
                        "primary", variant, "124M", 900, 0, 1,
                        (f"lr={lr}", f"weight_decay={wd}", f"scalar_lr_mult={scalar}"),
                        "ASTRO structural variant x LR/WD/scalar sensitivity",
                    ))

    return jobs


def _jobs_mechanisms() -> list[Job]:
    """Focused component attribution at several training horizons and seeds."""
    jobs: list[Job] = []

    variants = (
        "muon",
        "astro",
        "astro_muon_betas",
        "astro_v2",
        "astro_cautious",
        "astro_plain_wd",
        "astro_wd_rescaled",
        "astro_converging",
        "astro_equil",
        "astro_trust",
        "astro_nosplit",
        "astro_split100",
        "astro_split300",
        "astro_v2_gamma0",
    )

    # Use a small fixed set around the already observed scalar path so the
    # component differences are not confounded by a massive search.
    for steps in (300, 900, 2700):
        for seed in (0, 1, 2):
            for variant in variants:
                jobs.append(_make(
                    "mechanisms", variant, "124M", steps, seed, 1,
                    ("lr=0.0144", "weight_decay=0.02", "scalar_lr_mult=0.4369"),
                    "component attribution across horizon/seed",
                ))

    # Scalar-path beta asymmetry deserves an independent sweep because the
    # preliminary data suggest it may dominate the bundled ASTRO gain.
    for b1 in (0.9, 0.95, 0.98, 0.99):
        for b2 in (0.9, 0.95, 0.98, 0.99):
            for seed in (0, 1, 2):
                jobs.append(_make(
                    "mechanisms", "astro", "124M", 900, seed, 1,
                    ("lr=0.0144", "weight_decay=0.02", "scalar_lr_mult=0.4369",
                     f"beta1={b1}", f"beta2={b2}"),
                    "explicit beta1/beta2 sensitivity",
                ))

    # NS iteration / polar schedule sensitivity.
    for variant in ("astro", "astro_converging"):
        for steps_ns in (3, 4, 5, 6, 7):
            for seed in (0, 1, 2):
                jobs.append(_make(
                    "mechanisms", variant, "124M", 900, seed, 1,
                    ("lr=0.0144", "weight_decay=0.02", "scalar_lr_mult=0.4369",
                     f"ns_steps={steps_ns}"),
                    "polar iteration budget sensitivity",
                ))

    return jobs


def _jobs_robustness() -> list[Job]:
    """Scale and horizon transfer checks with a compact but symmetric design."""
    jobs: list[Job] = []
    opts = ("muon", "normuon", "adamuon", "soap", "astro_v2", "astro_muon_betas", "astro")

    # Search at 124M, then freeze the central recipe while testing model scale.
    for size in ("45M", "124M", "355M"):
        for steps in (300, 900, 2700):
            for opt in opts:
                for seed in (0, 1, 2):
                    pins = ("lr=0.0144", "weight_decay=0.02", "scalar_lr_mult=0.4369")
                    jobs.append(_make(
                        "robustness", opt, size, steps, seed, 1, pins,
                        "scale x horizon x seed transfer",
                    ))

    # Optimizer-specific LR transfer: test whether the baseline winner merely
    # sits on a different update scale. Each optimizer gets the same multiplicative
    # factors around its nominal tuned point.
    for opt in opts:
        for factor in (0.5, 0.75, 1.0, 1.33, 2.0):
            for seed in (0, 1, 2):
                jobs.append(_make(
                    "robustness", opt, "124M", 900, seed, 1,
                    (f"lr={0.0144 * factor:.7g}", "weight_decay=0.02", "scalar_lr_mult=0.4369"),
                    "LR transfer sensitivity",
                ))

    return jobs


def _jobs_stability() -> list[Job]:
    """Failure/sanity campaign: longer runs, high/low decay, and extreme LR."""
    jobs: list[Job] = []
    opts = ("muon", "normuon", "adamuon", "astro_v2", "astro_muon_betas", "astro")
    for opt in opts:
        for lr in (0.0015, 0.003, 0.006, 0.012, 0.024, 0.048, 0.096, 0.192):
            for wd in (0.0, 0.01, 0.1, 0.3):
                jobs.append(_make(
                    "stability", opt, "124M", 2700, 0, 1,
                    (f"lr={lr}", f"weight_decay={wd}", "scalar_lr_mult=0.4369"),
                    "long-horizon stability envelope",
                ))
    return jobs


def _make(suite, optimizer, size, steps, seed, trials, pins, purpose) -> Job:
    jid = _job_id(suite, optimizer, size, steps, seed, trials, *pins)
    return Job(
        job_id=jid,
        suite=suite,
        optimizer=optimizer,
        size=size,
        steps=steps,
        seed=seed,
        trials=trials,
        pins=tuple(pins),
        purpose=purpose,
        shard_key=jid,
    )


def build_jobs(suite: str) -> list[Job]:
    builders = {
        "primary": _jobs_primary,
        "mechanisms": _jobs_mechanisms,
        "robustness": _jobs_robustness,
        "stability": _jobs_stability,
    }
    if suite == "all":
        jobs: list[Job] = []
        for name in builders:
            jobs.extend(builders[name]())
        return jobs
    return builders[suite]()


def shard(jobs: Iterable[Job], spec: str) -> list[Job]:
    part_s, total_s = spec.split("/", 1)
    part, total = int(part_s), int(total_s)
    if total < 1 or not (0 <= part < total):
        raise ValueError("--shard must be PART/TOTAL with 0 <= PART < TOTAL")
    return [job for i, job in enumerate(jobs) if i % total == part]


def _read_completed(log_path: Path) -> set[str]:
    done: set[str] = set()
    if not log_path.exists():
        return done
    with log_path.open("r", encoding="utf-8") as f:
        for line in f:
            try:
                rec = json.loads(line)
            except json.JSONDecodeError:
                continue
            if rec.get("status") == "completed":
                done.add(str(rec.get("job_id")))
    return done


def _append_jsonl(path: Path, rec: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("a", encoding="utf-8") as f:
        f.write(json.dumps(rec, sort_keys=True) + "\n")


def _write_manifest(path: Path, jobs: list[Job], argv: list[str]) -> None:
    payload = {
        "schema_version": 1,
        "created_at_unix": time.time(),
        "launcher_argv": argv,
        "job_count": len(jobs),
        "jobs": [asdict(j) for j in jobs],
    }
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def estimate_hours(jobs: list[Job], seconds_per_step: float = 1.2) -> float:
    total_steps = sum(j.steps for j in jobs)
    # This is deliberately only a rough planning number; model-size/batch and
    # polar iteration cost make wall-clock scale non-linearly.
    return total_steps * seconds_per_step / 3600.0


def run(args: argparse.Namespace) -> int:
    jobs = build_jobs(args.suite)
    if args.shard:
        jobs = shard(jobs, args.shard)
    if args.max_jobs is not None:
        jobs = jobs[: args.max_jobs]

    root = Path(args.work_root).expanduser().resolve()
    root.mkdir(parents=True, exist_ok=True)
    manifest = root / f"{args.suite}_manifest_{args.shard.replace('/', '_') if args.shard else 'all'}.json"
    log = root / "ablation_audit.jsonl"
    _write_manifest(manifest, jobs, sys.argv)

    print(f"suite={args.suite} jobs={len(jobs)} rough_hours={estimate_hours(jobs):.1f}")
    print(f"manifest={manifest}")
    print(f"audit={log}")

    completed = _read_completed(log)
    script = Path(args.astro_lab).expanduser().resolve()
    if not script.exists():
        raise FileNotFoundError(f"astro_lab.py not found: {script}")

    rc = 0
    for index, job in enumerate(jobs, 1):
        if job.job_id in completed:
            print(f"[{index}/{len(jobs)}] SKIP {job.job_id} {job.optimizer} {job.size} {job.steps}")
            continue

        job_dir = root / args.suite / job.job_id
        job_dir.mkdir(parents=True, exist_ok=True)
        cmd = job.command(script, job_dir)
        started = time.time()
        env = os.environ.copy()
        env.setdefault("PYTHONUNBUFFERED", "1")
        rec = {
            "job_id": job.job_id,
            "suite": job.suite,
            "optimizer": job.optimizer,
            "size": job.size,
            "steps": job.steps,
            "seed": job.seed,
            "pins": list(job.pins),
            "purpose": job.purpose,
            "status": "started",
            "started_at_unix": started,
            "command": cmd,
        }
        _append_jsonl(log, rec)

        print("\n" + "=" * 88)
        print(f"[{index}/{len(jobs)}] RUN {job.job_id} :: {job.optimizer} :: {job.size} :: {job.steps}")
        print(shlex.join(cmd))
        print("=" * 88)
        try:
            result = subprocess.run(cmd, env=env, check=False, timeout=args.timeout_minutes * 60)
            status = "completed" if result.returncode == 0 else "failed"
            rc = rc or result.returncode
        except subprocess.TimeoutExpired:
            status = "timeout"
            rc = rc or 124
            result = None

        ended = time.time()
        _append_jsonl(log, {
            **rec,
            "status": status,
            "ended_at_unix": ended,
            "duration_seconds": ended - started,
            "returncode": None if result is None else result.returncode,
            "work_dir": str(job_dir),
        })

        if status != "completed" and args.stop_on_error:
            print(f"Stopping after {status}: {job.job_id}")
            break

    print("\nCampaign finished. Re-run the same command to resume completed jobs.")
    return rc


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--suite", choices=("primary", "mechanisms", "robustness", "stability", "all"), default="primary")
    p.add_argument("--shard", help="PART/TOTAL, e.g. 0/3")
    p.add_argument("--max-jobs", type=int)
    p.add_argument("--dry-run", action="store_true")
    p.add_argument("--astro-lab", default=str(Path(__file__).with_name("astro_lab.py"))
    p.add_argument("--work-root", default="./artifacts/ablation")
    p.add_argument("--timeout-minutes", type=int, default=180)
    p.add_argument("--stop-on-error", action="store_true")
    args = p.parse_args()

    jobs = build_jobs(args.suite)
    if args.shard:
        jobs = shard(jobs, args.shard)
    if args.max_jobs is not None:
        jobs = jobs[: args.max_jobs]

    if args.dry_run:
        print(f"suite={args.suite} jobs={len(jobs)} rough_hours={estimate_hours(jobs):.1f}")
        for i, job in enumerate(jobs[: args.max_jobs or len(jobs)], 1):
            print(f"{i:5d} {job.job_id} {job.optimizer:20s} {job.size:5s} {job.steps:4d} {' '.join(job.pins)}")
        return 0

    return run(args)


if __name__ == "__main__":
    raise SystemExit(main())
