#!/usr/bin/env python3
"""Generate ORBIT LaTeX result macros/tables and optionally compile the paper."""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
from pathlib import Path


def tex_escape(value: str) -> str:
    return (
        value.replace("\\", "\\textbackslash{}")
        .replace("_", "\\_")
        .replace("%", "\\%")
        .replace("&", "\\&")
        .replace("#", "\\#")
    )


def write_generated(summary: dict, paper_dir: Path) -> None:
    confirm = summary.get("confirm", {})
    lines = ["% AUTO-GENERATED by scripts/orbit_build_paper.py. Do not edit."]
    if "orbit" in confirm:
        orbit = confirm["orbit"]
        lines.append(f"\\newcommand{{\\OrbitConfirmLoss}}{{{orbit['mean_val_loss']:.4f}}}")
        lines.append(f"\\newcommand{{\\OrbitConfirmSD}}{{{orbit['sd_val_loss']:.4f}}}")
    else:
        lines += [
            "\\newcommand{\\OrbitConfirmLoss}{TBD}",
            "\\newcommand{\\OrbitConfirmSD}{TBD}",
        ]
    if "muon" in confirm:
        muon = confirm["muon"]
        lines.append(f"\\newcommand{{\\MuonConfirmLoss}}{{{muon['mean_val_loss']:.4f}}}")
    else:
        lines.append("\\newcommand{\\MuonConfirmLoss}{TBD}")

    lines.append("")
    lines.append("\\begin{table}[t]")
    lines.append("\\centering")
    lines.append("\\caption{Held-out 124M confirmation. Lower validation loss is better.}")
    lines.append("\\label{tab:confirm}")
    lines.append("\\begin{tabular}{lrrrr}")
    lines.append("\\toprule")
    lines.append("Optimizer & $n$ & Mean loss & SD & Mean min. \\\\")
    lines.append("\\midrule")
    if confirm:
        for name, row in sorted(confirm.items(), key=lambda kv: kv[1]["mean_val_loss"]):
            lines.append(
                f"{tex_escape(name)} & {row['n']} & {row['mean_val_loss']:.4f} & "
                f"{row['sd_val_loss']:.4f} & {row['mean_seconds'] / 60:.1f} \\\\")
    else:
        lines.append("No confirmatory measurements yet & -- & -- & -- & -- \\\\")
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("\\end{table}")
    (paper_dir / "generated_results.tex").write_text("\n".join(lines) + "\n")


def sync_figures(work_dir: Path, paper_dir: Path) -> None:
    source = work_dir / "figures"
    target = paper_dir / "figures"
    target.mkdir(parents=True, exist_ok=True)
    if not source.exists():
        return
    for path in source.glob("*.pdf"):
        shutil.copy2(path, target / path.name)


def compile_tex(paper_dir: Path) -> None:
    if shutil.which("latexmk"):
        subprocess.run(
            ["latexmk", "-pdf", "-interaction=nonstopmode", "-halt-on-error", "main.tex"],
            cwd=paper_dir,
            check=True,
        )
        return
    if shutil.which("pdflatex"):
        subprocess.run(["pdflatex", "-interaction=nonstopmode", "main.tex"], cwd=paper_dir, check=True)
        if shutil.which("bibtex"):
            subprocess.run(["bibtex", "main"], cwd=paper_dir, check=False)
        subprocess.run(["pdflatex", "-interaction=nonstopmode", "main.tex"], cwd=paper_dir, check=True)
        subprocess.run(["pdflatex", "-interaction=nonstopmode", "main.tex"], cwd=paper_dir, check=True)
        return
    raise SystemExit("No latexmk/pdflatex found. Generated TeX is ready; install TeX Live to compile.")


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("--work-dir", type=Path, required=True)
    p.add_argument("--paper-dir", type=Path, default=Path("docs/orbit/paper"))
    p.add_argument("--no-compile", action="store_true")
    args = p.parse_args()
    summary_path = args.work_dir / "merged" / "summary.json"
    summary = json.loads(summary_path.read_text()) if summary_path.exists() else {}
    args.paper_dir.mkdir(parents=True, exist_ok=True)
    write_generated(summary, args.paper_dir)
    sync_figures(args.work_dir, args.paper_dir)
    print(f"generated results -> {args.paper_dir / 'generated_results.tex'}")
    if not args.no_compile:
        compile_tex(args.paper_dir)
        print(f"paper -> {args.paper_dir / 'main.pdf'}")


if __name__ == "__main__":
    main()
